- id: SovrinMainNet
  is_production: true
  genesis_url: 'https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_live_genesis'
- id: BCovrinTest
  is_production: true
  genesis_url: 'http://test.bcovrin.vonx.io/genesis'
- id: CANdyProd
  is_production: true
  genesis_url: 'https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/prod/pool_transactions_genesis'
