{{- if (include "acapy.createSecret" .) }}
{{- $secretName := include "acapy.secretName" . -}}
{{- $adminApiKey := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $secretName "Key" "adminApiKey" "Length" 32) -}}
{{- $walletKey := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $secretName "Key" "walletKey" "Length" 32) -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "acapy.secretName" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if not (index .Values "acapy" "argfile.yml" "admin-insecure-mode") }}
  adminApiKey: {{ $adminApiKey }}
  {{- end }}
  walletKey: {{ $walletKey }}
{{- end }}
---
{{- if (include "acapy.seed.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "acapy.fullname" . }}
  labels:
    {{- include "acapy.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  seed: {{ include "acapy.seed" . }}
{{- end }}
