version: '3'

services:
  database:
    image: postgres:10.6
    environment:
      - POSTGRES_USER=identity
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
  keycloak:
    image: jboss/keycloak:7.0.0
    ports:
      - 8180:8080
    volumes:
      - ./keycloak/config:/tmp
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/master.json
  aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.15-0_0.5.2
    ports:
      - 5678:5678 
      - 5679:5679
    command: [ "start", "-it", "http", "0.0.0.0", "5679", "-ot", "http",  "--log-level", "DEBUG", "--webhook-url", "https://localhost:5001", "--admin", "0.0.0.0", "5678", "--admin-insecure-mode", "test", "--seed", "000000000000000000000000Steward1" ]
