- id: BCovrinTest
  is_production: true
  genesis_url: 'http://test.bcovrin.vonx.io/genesis'
- id: SovrinStagingNet
  is_production: true
  genesis_url: 'https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_sandbox_genesis'
- id: CANdyDev
  is_production: true
  genesis_url: 'https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/dev/pool_transactions_genesis'
- id: CANdyTest
  is_production: true
  is_write: true
  genesis_url: 'https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/test/pool_transactions_genesis'
