{{- if or .Values.networkPolicy.enabled .Values.networkPolicy.ingress.enabled -}}
apiVersion: v1
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "global.fullname" . }}-ingress
  labels:
    {{- include "vc-authn-oidc.labels" . | nindent 4 }}
spec:
  #  Allow ingress traffic into the controller
  ingress:
     {{- if and .Values.ingress.enabled .Values.networkPolicy.ingress.enabled (or .Values.networkPolicy.ingress.namespaceSelector .Values.networkPolicy.ingress.podSelector) }}
    - from:
        {{- if .Values.networkPolicy.ingress.namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.ingress.namespaceSelector "context" $) | nindent 14 }}
        {{- end }}
        {{- if .Values.networkPolicy.ingress.podSelector }}
        - podSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.ingress.podSelector "context" $) | nindent 14 }}
        {{- end }}
    {{- end }}
  podSelector:
    matchLabels:
      {{- include "vc-authn-oidc.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
{{- end -}}
 ---
{{- if and .Values.acapy.networkPolicy.enabled .Values.acapy.networkPolicy.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "acapy.fullname" . }}-ingress
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "acapy.selectorLabels" . | nindent 6 }}
  ingress:
     {{- if and .Values.ingress.enabled .Values.acapy.networkPolicy.ingress.enabled (or .Values.acapy.networkPolicy.ingress.namespaceSelector .Values.acapy.networkPolicy.ingress.podSelector) }}
    - from:
        {{- if .Values.acapy.networkPolicy.ingress.namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .Values.acapy.networkPolicy.ingress.namespaceSelector "context" $) | nindent 14 }}
        {{- end }}
        {{- if .Values.acapy.networkPolicy.ingress.podSelector }}
        - podSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .Values.acapy.networkPolicy.ingress.podSelector "context" $) | nindent 14 }}
        {{- end }}
    {{- end }}
  policyTypes:
    - Ingress
{{- end -}}
